config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} # use custom registrations controller
  resources :listings
  resources :users, only:[:index, :show, :edit, :update]

  # Root/Homepage
  get "/", to: "pages#home", as: "root"

  post "/payments", to: "listings#payment", as: "payment"

  # Successful Payment Page
  get "/success", to: "pages#success", as: "success"
  # Cancel Payment Page
  get "/cancel", to: "pages#cancel", as: "cancel"

  # Privacy Policy Page
  get "/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"

  # Terms and Conditions Page
  get "/terms", to: "pages#terms", as: "terms"

  get "/listings/:id/rating", to: "pages#rating", as: "rating"
  
  post "/listings/:id/rating", to: "pages#set_rating"
  # post "/listings/:id/rating", to: "pages"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one :product_order
  has_one_attached :picture
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
  validates :price, presence: true, numericality: { greater_than: 5,  only_integer: true }
  validates :rating, numericality: { only_integer: true, allow_blank: true }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :payment]
  before_action :set_purchased_and_unpurchased_listings, only: [:index, :show]
  skip_before_action :verify_authenticity_token, only: [:payment]
  # GET /listings
  # GET /listings.json
  def index
    
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @mark = @listing.show_phone
    if user_signed_in?
      unless @listing.product_order
        stripe_session = Stripe::Checkout::Session.create(
          payment_method_types: ['card'],
          client_reference_id: current_user.id,
          line_items: [{
            name: @listing.title,
            description: @listing.description,
            amount: @listing.price * 100, #Basic unit of stripe payment is cent.
            currency: 'aud',
            quantity: 1
          }],
          payment_intent_data: {
            metadata: {
              listing_id: @listing.id
            }
          },
          success_url: success_url,
          cancel_url: cancel_url
        )
        @stripe_session_id = stripe_session.id
      end
    end
  end

  # GET /listings/new
  def new
    @listing = current_user.listings.build 
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create

    @listing = current_user.listings.build(listing_params)
    # The default value of the rating of the listing when created is 5
    @listing.rating = 5 
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payment
    payment_id = params[:data][:object][:payment_intent]
    payment = Stripe::PaymentIntent.retrieve(payment_id)
    ProductOrder.create(user_id: params[:data][:object]["client_reference_id"], listing_id: payment["metadata"]["listing_id"])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :price, :description, :phone_number, :picture, :show_phone, :rating)
    end

    def set_purchased_and_unpurchased_listings
      @listings = Listing.all.order('id DESC')
      @purchased_listings = Listing.joins(:product_order)
      @unpurchased_listings = @listings - @purchased_listings
      byebug
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <!--
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
      -->
      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group form-row">
    <div class="col-sm-4 col-form-label">
      <%= label_tag :title, "Listing Title: " %>
    </div>
    <div class="col-sm-8">
      <%= form.text_field :title, class: "form-control", data: {cy: "title"}%>
    </div>
  </div><!-- end of row -->
  
  <div class="field form-group form-row">
    <div class="col-sm-4 col-form-label">
      <%= label_tag :price, "Price: " %>
    </div>
    <div class="col-sm-8">
      <%= form.number_field :price, min: 5,class: "form-control", data: {cy: "price"}%>
    </div>
  </div><!-- end of row -->
  
  <div class="field form-group form-row">
    <div class="col-sm-4 col-form-label">
      <%= label_tag :description, "Description: " %>
    </div>
    <div class="col-sm-8">
      <%= form.text_area :description, class: "form-control", data: {cy: "description"}%>
    </div>
  </div><!-- end of row -->

  <div class="field form-group form-row">
    <div class="col-sm-4 col-form-label">
      <%= label_tag :picture, "Picture" %>
    </div>
    <div class="col-sm-8">
      <% if listing.picture.attached? %>
        <div class="row mb-2">
          <div class="col-sm-6">
            <%= image_tag listing.picture, class: "img-fluid" %> 
          </div>
          <div class="col"></div>
        </div>
      <% end %>
      <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg', class: "form-control-file" %>
    </div>
  </div><!-- end of row -->
  
  <div class="field form-group form-row">
    <div class="col-sm-4 col-form-label">
      <%= label_tag :show_phone, "Show my phone number:" %>
    </div>
    <div class="col-sm-8">
      <%= form.radio_button :show_phone, true, data: {cy: "showphone"} %> Yes<br />
      <%= form.radio_button :show_phone, false, data: {cy: "hidephone"} %> No
    </div>
  </div><!-- end of row -->

  <div class="actions mb-4 form-row">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-8">
      <%= form.submit "Submit", class: "btn btn-primary form-control-inline", data: {cy: "submit"} %>
    </div>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div id="edit-listing">
  <h2 class="mb-4">Editing Listing</h2>

  <%= render 'form', listing: @listing %>

  <div class="row mb-4">
    <div class="col-sm-4"></div>
    <div class="col-sm-8 pl-2">
      <%= link_to 'Go Back', listings_path, class: "btn btn-secondary mr-2" %>
      <%= link_to 'View Listing', @listing, class: "btn btn-secondary" %> 
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<h2 class="text-center mb-4">Browse Listings</h2>
<div class="text-center mb-4">
    <%= link_to 'Create a Listing', new_listing_path, class: "btn btn-primary" %>
</div>

<div id="listings-container" class="container">

  <% @unpurchased_listings.each_with_index do |listing, index| %>

    <% if index == 0 # the very first listing %>
      <div class="row"><!-- open .row -->
    <% end %>

    <%# first listing in the row (excluding the very first listing) %>
    <% if index != 0 && (index + 1) % 3 == 1 %>
      </div><!-- close ."row" -->
      <div class="row"><!-- open .row -->
    <% end %>

    <div class="col-sm-4 text-center"><!-- open column -->
      <div class="container">
        <div class="listing-image">  
            <% unless listing.picture.attached? and user_signed_in? and listing.user_id == current_user.id %>
              <%= link_to image_tag('defaultbox.jpg', class: "img-thumbnail"), listing %>
            <% else %>
              <%= link_to image_tag(listing.picture, class: "img-thumbnail"), listing %>
            <% end %>
        </div><!-- end of .listing-image -->

        <div class="listing-content mt-4">
          <h5>
            <%= listing.title %>
          </h5>
          <p>
            $<%= listing.price.to_f.round(2) %>
          </p>
          <p>
            <%= link_to 'View Listing', listing, class: "btn btn-primary btn-xs" %>
            <% if current_user && listing.user == current_user %>
              <%= link_to '<span class="badge badge-warning">Edit</span>'.html_safe, edit_listing_path(listing) %>
              <%= link_to '<span class="badge badge-danger">Remove</span>'.html_safe, listing, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        </div><!-- end of .listing-content -->
      </div><!-- end of .container -->
    </div><!-- close column -->

    <% if listing == @listings.last %>
      <% remaining_columns = 3 - (@listings.count % 3) %>
      <% if remaining_columns > 0 && remaining_columns < 3 %>
        <% remaining_columns.times do %>
          <div class="col-sm-4"></div>
        <% end %>
      <% end %>
      </div><!-- close .row -->
    <% end %>

  <% end # @listing.each_with_index%>
</div>

app/views/listings/new.html.erb
<div id="new-listing">
  <h2 class="mb-4">New Listing</h2>

  <%= render 'form', listing: @listing %>

  <div class="row mb-4">
    <div class="col-sm-4"></div>
    <div class="col-sm-8 pl-2">
      <%= link_to 'Go Back', listings_path, class: "btn btn-secondary mr-2" %>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div id="listings-page">
    <h2 class="py-4 text-center"><%= @listing.title %></h2>

    <div class="row mb-4">

        <div class="col-sm-4 text-center">
            <% unless @listing.picture.attached? and user_signed_in? and @listing.user_id == current_user.id %>
                <p ><%= image_tag('defaultbox.jpg', class: "img-fluid") %></p>
            <% else %>
                <p><%= image_tag(@listing.picture, class: "img-fluid") %></p>
            <% end %>
            
            <% if current_user && @listing.user == current_user %>
              <p><%= link_to 'Edit your Listing', edit_listing_path(@listing) %></p> 
            <% end %>
          
            <div id="listing-data">
                <p><%= link_to @listing.user.username, user_path(@listing.user.id), :class => "btn btn-info" %></p>
                <p>Item Price: $<%= number_with_precision(@listing.price, precision: 2) %></p>
                <!-- stripe payment won't show up if they aren't signed in -->
                <% unless @listing.product_order %>
                    <% if user_signed_in? %>
                        <p><button id="stripePayment" class="btn btn-primary"><i class="fas fa-shopping-cart"></i>&nbsp;&nbsp;Buy It Now</button></p>
                    <% else %>
                        <p>You must <%= link_to "Sign Up", new_user_registration_path  %> or 
                        <%= link_to "Sign In", new_user_session_path %> to make a purchase.</p>
                    <% end %>
                <% else %>
                    <% if @listing.product_order.user == current_user %>
                        <% unless @listing.rating.present? %>
                            <p><span class="badge badge-success">You Purchased This!</span></p>
                            <%= form_for :listing, method: "put" do |f| %>
                                <%= label_tag(:rating, "Leave a Rating: ") %>
                                <%= f.number_field(:rating, within: 1..5) %> / 5<br />
                                <%= f.submit("Submit", class: "btn btn-primary btn-xs") %>
                            <% end %>
                        <% else %>
                            <p>
                                <span class="badge badge-success">
                                    You Rated: <%= @listing.rating %> / 5
                                </span>
                            </p>
                        <% end %>
                    <% else %>
                        <span class="badge badge-danger">SOLD</span> to
                        <%= @listing.product_order.user.username %>
                        <% if @listing.rating.present? %>
                            <br />
                            Rating: <span class="badge badge-primary"><%= @listing.rating %> / 5</span>
                        <% end %>
                    <% end %>
                <% end %>
            </div><!-- end of #listing-data -->
            <% if user_signed_in? && @mark == true %>
                <h6>Contact The Seller</h6>
                <p><%= @listing.user.phone_number %></p>
            <% end %>
        </div><!-- end of column -->
            
        <div class="col-sm-8 text-center">
            <h5 class="mb-4"><strong>Description</strong></h5>
            <p><%= @listing.description %></p>
            <p><%= link_to 'Back', listings_path, class: "btn btn-secondary mt-2" %></p>
        </div><!-- end of column -->

    </div><!-- end of row -->

</div><!-- end of #listings-page -->

<script>
    document.getElementById("stripePayment").addEventListener("click", function() {
      
      var stripe = Stripe('<%= Rails.application.credentials.dig(:stripe, :public) %>');

      stripe.redirectToCheckout({
        sessionId: '<%= @stripe_session_id %>',
      }).then(function (result) {
        // If `redirectToCheckout` fails due to a browser or network
        // error, display the localized error message to your customer
        // using `result.error.message`.
      });
    });
</script>