config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} # use custom registrations controller
  resources :listings
  resources :users, only:[:index, :show, :edit, :update]

  # Root/Homepage
  get "/", to: "pages#home", as: "root"

  post "/payments", to: "listings#payment", as: "payment"

  # Successful Payment Page
  get "/success", to: "pages#success", as: "success"
  # Cancel Payment Page
  get "/cancel", to: "pages#cancel", as: "cancel"

  # Privacy Policy Page
  get "/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"

  # Terms and Conditions Page
  get "/terms", to: "pages#terms", as: "terms"

  get "/listings/:id/rating", to: "pages#rating", as: "rating"
  
  post "/listings/:id/rating", to: "pages#set_rating"
  # post "/listings/:id/rating", to: "pages"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/cancel.html.erb
<div id="cancelled-payment">

  <p>Cancelled Payment</p>

</div>

app/views/pages/home.html.erb
<div id="homepage">
  <!-- Slogan -->
  <h5 id="slogan" class="py-5 text-center text-muted">One person's mysterious trash is another's mysterious treasure.</h5>

  <% if @highest_priced_sale and @lowest_priced_sale %>
    <div id="extremes" class="row mb-5">
      <div class="col-sm-6 text-center">
        <%# Highest priced sale %>
        <% if @highest_priced_sale.picture.attached? %>
          <%= link_to image_tag(@highest_priced_sale.picture, class: "img-thumbnail"), listing_path(@highest_priced_sale.id) %>
        <% else %>
          <%= link_to image_tag('defaultbox.jpg', class: "img-thumbnail"), listing_path(@highest_priced_sale.id) %>
        <% end %>
        <h3 class="my-4"><%= @highest_priced_sale.title %></h3>
        <p class="h3">
          <del>$<%= @highest_priced_sale.price %></del>
          <span class="badge badge-success">SOLD</span>
        </p>
        <div class="description">
          <small><em><%= @highest_priced_sale.description %></em></small>
        </div>
      </div><!-- end of column -->

      <div class="col-sm-6 text-center">
        <%# Lowest priced sale %>
        <% if @lowest_priced_sale.picture.attached? %>
          <%= link_to image_tag(@lowest_priced_sale.picture, class: "img-thumbnail"), listing_path(@lowest_priced_sale.id) %>
        <% else %>
          <%= link_to image_tag('defaultbox.jpg', class: "img-thumbnail"), listing_path(@lowest_priced_sale.id) %>
        <% end %>
        <h3 class="my-4"><%= @lowest_priced_sale.title %></h3>
        <p class="h3">
          <del>$<%= @lowest_priced_sale.price %></del>
          <span class="badge badge-success">SOLD</span>
        </p>
        <div class="description">
          <small><em><%= @lowest_priced_sale.description %></em></small>
        </div>
      </div><!-- end of column -->
    </div><!-- end of #extremes -->
  <% end # (if @highest_priced_sale and @lowest_priced_sale) %>

  <!-- Browse Listings Enticement -->
  <div id="browse-enticement" class="row mb-4">
    <div class="col-sm-4 text-center">
      <%# Find a new image to put here %>
      <%= image_tag "transparent-mystery-box.jpg", class: "img-fluid mb-2" %>
    </div>
    <div class="col-sm-8">
      <h3 class="mb-4">Buy Something Mysterious...</h3>
      <p>Zombie ipsum reversus ab viral, nam rick grimes malum cerebro. De carne  corpora quaeritis.</p>
      <p>Summus brains sit​​, morbo vel maleficia?</p>
      <p>De apocalypsi gorger omero undead survivor dictum mauris!</p>
      <p>
        <%= link_to "Browse Listings", listings_path, class: "btn btn-primary" %>
      </p>
    </div>
  </div><!-- end of #browse-enticement.row -->

  <!-- Create Listing Enticement -->
  <div id="sell-enticement" class="row mb-4">
    <div class="col-sm-4 text-center">
      <%# Find a new image to put here %>
      <%= image_tag "yard-sale-kid.jpg", class: "img-fluid mb-2" %>
    </div>
    <div class="col-sm-8">
      <h3 class="mb-4">Have stuff to sell?</h3>
      <p>The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus.</p>
      <p>Qui animated corpse, cricket bat max brucks terribilem incessu zomby.</p>
      <p>
        <%= link_to "Create a Listing", new_listing_path, class: "btn btn-primary" %>
      </p>
    </div>
  </div><!-- end of #sell-enticement.row -->

</div><!-- end of #homepage -->

app/views/pages/privacy_policy.html.erb
<div id="privacy-policy">
  <h1 class="my-4">Privacy Policy</h1>
  <h3 class="my-4">Your privacy is critically important to us.</h3 class="my-4">
  Mystery Box Market is located at:<br/>
  <address>
  Mystery Box Market<br/><br/>Contact: 0432171252			</address>

  <p>It is Mystery Box Market's policy to respect your privacy regarding any information we may collect while operating our website. This Privacy Policy applies to <a href="https://www.mysteryboxmarket.space">https://www.mysteryboxmarket.space</a> (hereinafter, "us", "we", or "https://www.mysteryboxmarket.space"). We respect your privacy and are committed to protecting personally identifiable information you may provide us through the Website. We have adopted this privacy policy ("Privacy Policy") to explain what information may be collected on our Website, how we use this information, and under what circumstances we may disclose the information to third parties. This Privacy Policy applies only to information we collect through the Website and does not apply to our collection of information from other sources.</p>
  <p>This Privacy Policy, together with the Terms and conditions posted on our Website, set forth the general rules and policies governing your use of our Website. Depending on your activities when visiting our Website, you may be required to agree to additional terms and conditions.</p>

  <h2 class="my-4">Website Visitors</h2 class="my-4">
  <p>Like most website operators, Mystery Box Market collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. Mystery Box Market's purpose in collecting non-personally identifying information is to better understand how Mystery Box Market's visitors use its website. From time to time, Mystery Box Market may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>
  <p>Mystery Box Market also collects potentially personally-identifying information like Internet Protocol (IP) addresses for logged in users and for users leaving comments on https://www.mysteryboxmarket.space blog posts. Mystery Box Market only discloses logged in user and commenter IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below.</p>

  <h2 class="my-4">Gathering of Personally-Identifying Information</h2 class="my-4">
  <p>Certain visitors to Mystery Box Market's websites choose to interact with Mystery Box Market in ways that require Mystery Box Market to gather personally-identifying information. The amount and type of information that Mystery Box Market gathers depends on the nature of the interaction. For example, we ask visitors who sign up for a blog at https://www.mysteryboxmarket.space to provide a username and email address.</p>

  <h2 class="my-4">Security</h2 class="my-4">
  <p>The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>

  <h2 class="my-4">Advertisements</h2 class="my-4">
  <p>Ads appearing on our website may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by Mystery Box Market and does not cover the use of cookies by any advertisers.</p>


  <h2 class="my-4">Links To External Sites</h2 class="my-4">
  <p>Our Service may contain links to external sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy and terms and conditions of every site you visit.</p>
  <p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites, products or services.</p>


  <h2 class="my-4">Protection of Certain Personally-Identifying Information</h2 class="my-4">
  <p>Mystery Box Market discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on Mystery Box Market's behalf or to provide services available at Mystery Box Market's website, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using Mystery Box Market's website, you consent to the transfer of such information to them. Mystery Box Market will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, Mystery Box Market discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when Mystery Box Market believes in good faith that disclosure is reasonably necessary to protect the property or rights of Mystery Box Market, third parties or the public at large.</p>
  <p>If you are a registered user of https://www.mysteryboxmarket.space and have supplied your email address, Mystery Box Market may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with Mystery Box Market and our products. We primarily use our blog to communicate this type of information, so we expect to keep this type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. Mystery Box Market takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>

  <h2 class="my-4">Aggregated Statistics</h2 class="my-4">
  <p>Mystery Box Market may collect statistics about the behavior of visitors to its website. Mystery Box Market may display this information publicly or provide it to others. However, Mystery Box Market does not disclose your personally-identifying information.</p>


  <h2 class="my-4">Cookies</h2 class="my-4">
  <p>To enrich and perfect your online experience, Mystery Box Market uses "Cookies", similar technologies and services provided by others to display personalized content, appropriate advertising and store your preferences on your computer.</p>
  <p>A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. Mystery Box Market uses cookies to help Mystery Box Market identify and track visitors, their usage of https://www.mysteryboxmarket.space, and their website access preferences. Mystery Box Market visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using Mystery Box Market's websites, with the drawback that certain features of Mystery Box Market's websites may not function properly without the aid of cookies.</p>
  <p>By continuing to navigate our website without changing your cookie settings, you hereby acknowledge and agree to Mystery Box Market's use of cookies.</p>

  <h2 class="my-4">E-commerce</h2 class="my-4">
  <p>Those who engage in transactions with Mystery Box Market – by purchasing Mystery Box Market's services or products, are asked to provide additional information, including as necessary the personal and financial information required to process those transactions. In each case, Mystery Box Market collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor's interaction with Mystery Box Market. Mystery Box Market does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>


  <h2 class="my-4">Privacy Policy Changes</h2 class="my-4">
  <p>Although most changes are likely to be minor, Mystery Box Market may change its Privacy Policy from time to time, and in Mystery Box Market's sole discretion. Mystery Box Market encourages visitors to frequently check this page for any changes to its Privacy Policy. Your continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.</p>


    
  <h2 class="my-4">Stripe Payments in Test Mode</h2 class="my-4">			  
  <p>Mysteryboxmarket.space checkout system uses Stripe Payments which will run in 'test mode' indefinitely.  Your credit/debit card will not be charged when you go through the purchase process on this website.  As such, users should not expect to receive goods purchased through this website.  This website was created purely for educational purposes and is not a business venture.</p>			

  <h2 class="my-4">Credit & Contact Information</h2 class="my-4">
    <p>This privacy policy was created at <a style="color:inherit;text-decoration:none;" href="https://termsandconditionstemplate.com/privacy-policy-generator/" title="Privacy policy template generator" target="_blank">termsandconditionstemplate.com</a>. If you have any questions about this Privacy Policy, please contact us via <a href="mailto:the.jim.farrugia@gmail.com">email</a> or <a href="tel:0432171252">phone</a>.</p>
</div>

app/views/pages/rating.html.erb
<h1>rate here</h1>

app/views/pages/success.html.erb
<div id="successful-payment">
  <h2 class="mb-4">Successful Payment</h2>
  <div>
      <%#= link_to "Click here to rate the item.", rating_path(id:@purchased_listing_id) %>
  </div>
</div>

app/views/pages/terms.html.erb
<div id="terms">
  <h1 class="my-4">Terms &amp; Conditions</h1 class="my-4">
  <p>These terms and conditions outline the rules and regulations for the use of Mystery Box Market's Website.</p>
  <p>By accessing this website we assume you accept these terms and conditions in full. Do not continue to use Mystery Box Market's website 
  if you do not accept all of the terms and conditions stated on this page.</p>
  <p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice
  and any or all Agreements: "Client", "You" and "Your" refers to you, the person accessing this website
  and accepting the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers
  to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves, or either the Client
  or ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake
  the process of our assistance to the Client in the most appropriate manner, whether by formal meetings
  of a fixed duration, or any other means, for the express purpose of meeting the Client's needs in respect
  of provision of the Company's stated services/products, in accordance with and subject to, prevailing law
  of . Any use of the above terminology or other words in the singular, plural,
  capitalisation and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p><h2 class="my-4">Cookies</h2 class="my-4">
  <p>We employ the use of cookies. By using Mystery Box Market's website you consent to the use of cookies 
  in accordance with Mystery Box Market's privacy policy.</p><p>Most of the modern day interactive web sites
  use cookies to enable us to retrieve user details for each visit. Cookies are used in some areas of our site
  to enable the functionality of this area and ease of use for those people visiting. Some of our 
  affiliate / advertising partners may also use cookies.</p><h2 class="my-4">License</h2 class="my-4">
  <p>Unless otherwise stated, Mystery Box Market and/or it's licensors own the intellectual property rights for
  all material on Mystery Box Market. All intellectual property rights are reserved. You may view and/or print
  pages from https://www.mysteryboxmarket.space for your own personal use subject to restrictions set in these terms and conditions.</p>
  <p>You must not:</p>
  <ol>
    <li>Republish material from https://www.mysteryboxmarket.space</li>
    <li>Sell, rent or sub-license material from https://www.mysteryboxmarket.space</li>
    <li>Reproduce, duplicate or copy material from https://www.mysteryboxmarket.space</li>
  </ol>
  <p>Redistribute content from Mystery Box Market (unless content is specifically made for redistribution).</p>
  <h2 class="my-4">Hyperlinking to our Content</h2 class="my-4">
  <ol>
    <li>The following organizations may link to our Web site without prior written approval:
      <ol>
      <li>Government agencies;</li>
      <li>Search engines;</li>
      <li>News organizations;</li>
      <li>Online directory distributors when they list us in the directory may link to our Web site in the same
        manner as they hyperlink to the Web sites of other listed businesses; and</li>
      <li>Systemwide Accredited Businesses except soliciting non-profit organizations, charity shopping malls,
        and charity fundraising groups which may not hyperlink to our Web site.</li>
      </ol>
    </li>
  </ol>
  <ol start="2">
    <li>These organizations may link to our home page, to publications or to other Web site information so long
      as the link: (a) is not in any way misleading; (b) does not falsely imply sponsorship, endorsement or
      approval of the linking party and its products or services; and (c) fits within the context of the linking
      party's site.
    </li>
    <li>We may consider and approve in our sole discretion other link requests from the following types of organizations:
      <ol>
        <li>commonly-known consumer and/or business information sources such as Chambers of Commerce, American
          Automobile Association, AARP and Consumers Union;</li>
        <li>dot.com community sites;</li>
        <li>associations or other groups representing charities, including charity giving sites,</li>
        <li>online directory distributors;</li>
        <li>internet portals;</li>
        <li>accounting, law and consulting firms whose primary clients are businesses; and</li>
        <li>educational institutions and trade associations.</li>
      </ol>
    </li>
  </ol>
  <p>We will approve link requests from these organizations if we determine that: (a) the link would not reflect
  unfavorably on us or our accredited businesses (for example, trade associations or other organizations
  representing inherently suspect types of business, such as work-at-home opportunities, shall not be allowed
  to link); (b)the organization does not have an unsatisfactory record with us; (c) the benefit to us from
  the visibility associated with the hyperlink outweighs the absence of <?=$companyName?>; and (d) where the
  link is in the context of general resource information or is otherwise consistent with editorial content
  in a newsletter or similar product furthering the mission of the organization.</p>

  <p>These organizations may link to our home page, to publications or to other Web site information so long as
  the link: (a) is not in any way misleading; (b) does not falsely imply sponsorship, endorsement or approval
  of the linking party and it products or services; and (c) fits within the context of the linking party's
  site.</p>

  <p>If you are among the organizations listed in paragraph 2 above and are interested in linking to our website,
  you must notify us by sending an e-mail to <a href="mailto:the.jim.farrugia@gmail.com" title="send an email to the.jim.farrugia@gmail.com">the.jim.farrugia@gmail.com</a>.
  Please include your name, your organization name, contact information (such as a phone number and/or e-mail
  address) as well as the URL of your site, a list of any URLs from which you intend to link to our Web site,
  and a list of the URL(s) on our site to which you would like to link. Allow 2-3 weeks for a response.</p>

  <p>Approved organizations may hyperlink to our Web site as follows:</p>

  <ol>
    <li>By use of our corporate name; or</li>
    <li>By use of the uniform resource locator (Web address) being linked to; or</li>
    <li>By use of any other description of our Web site or material being linked to that makes sense within the
      context and format of content on the linking party's site.</li>
  </ol>
  <p>No use of Mystery Box Market's logo or other artwork will be allowed for linking absent a trademark license
  agreement.</p>
  <h2 class="my-4">Iframes</h2 class="my-4">
  <p>Without prior approval and express written permission, you may not create frames around our Web pages or
  use other techniques that alter in any way the visual presentation or appearance of our Web site.</p>
  <h2 class="my-4">Reservation of Rights</h2 class="my-4">
  <p>We reserve the right at any time and in its sole discretion to request that you remove all links or any particular
  link to our Web site. You agree to immediately remove all links to our Web site upon such request. We also
  reserve the right to amend these terms and conditions and its linking policy at any time. By continuing
  to link to our Web site, you agree to be bound to and abide by these linking terms and conditions.</p>
  <h2 class="my-4">Removal of links from our website</h2 class="my-4">
  <p>If you find any link on our Web site or any linked web site objectionable for any reason, you may contact
  us about this. We will consider requests to remove links but will have no obligation to do so or to respond
  directly to you.</p>
  <p>Whilst we endeavour to ensure that the information on this website is correct, we do not warrant its completeness
  or accuracy; nor do we commit to ensuring that the website remains available or that the material on the
  website is kept up to date.</p>
  <h2 class="my-4">Content Liability</h2 class="my-4">
  <p>We shall have no responsibility or liability for any content appearing on your Web site. You agree to indemnify
  and defend us against all claims arising out of or based upon your Website. No link(s) may appear on any
  page on your Web site or within any context containing content or materials that may be interpreted as
  libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or
  other violation of, any third party rights.</p>
  <h2 class="my-4">Disclaimer</h2 class="my-4">
  <p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website (including, without limitation, any warranties implied by law in respect of satisfactory quality, fitness for purpose and/or the use of reasonable care and skill). Nothing in this disclaimer will:</p>
  <ol>
    <li>limit or exclude our or your liability for death or personal injury resulting from negligence;</li>
    <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
    <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
    <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
  </ol>
  <p>The limitations and exclusions of liability set out in this Section and elsewhere in this disclaimer: (a)
  are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer or
  in relation to the subject matter of this disclaimer, including liabilities arising in contract, in tort
  (including negligence) and for breach of statutory duty.</p>
  <p>To the extent that the website and the information and services on the website are provided free of charge,
  we will not be liable for any loss or damage of any nature.</p>
  <h2 class="my-4">Stripe Payments in Test Mode</h2 class="my-4">
  <p>Mysteryboxmarket.space checkout system uses Stripe Payments which will run in 'test mode' indefinitely.  Your credit/debit card will not be charged when you go through the purchase process on this website.  As such, users should not expect to receive goods purchased through this website.  This website was created purely for educational purposes and is not a business venture.</p>
  <h2 class="my-4">Credit & Contact Information</h2 class="my-4">
  <p>This Terms and conditions page was created at <a style="color:inherit;text-decoration:none;cursor:text;"
    href="https://termsandconditionstemplate.com">termsandconditionstemplate.com</a> generator. If you have
  any queries regarding any of our terms, please contact us.</p>
</div>