config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} # use custom registrations controller
  resources :listings
  resources :users, only:[:index, :show, :edit, :update]

  # Root/Homepage
  get "/", to: "pages#home", as: "root"

  post "/payments", to: "listings#payment", as: "payment"

  # Successful Payment Page
  get "/success", to: "pages#success", as: "success"
  # Cancel Payment Page
  get "/cancel", to: "pages#cancel", as: "cancel"

  # Privacy Policy Page
  get "/privacy_policy", to: "pages#privacy_policy", as: "privacy_policy"

  # Terms and Conditions Page
  get "/terms", to: "pages#terms", as: "terms"

  get "/listings/:id/rating", to: "pages#rating", as: "rating"
  
  post "/listings/:id/rating", to: "pages#set_rating"
  # post "/listings/:id/rating", to: "pages"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mystery Box Market</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!--Navbar-->
    <nav id="main-navbar" class="navbar sticky-top navbar-dark bg-dark mb-4" >
      <div class="container">
        <!-- Navbar brand -->
        <%= link_to "Mystery Box Market", root_path, class: "navbar-brand" %>
        <div class="welcome-user">
          <% if user_signed_in? %>
            <h5 class="mb-0">Welcome <%= current_user.username %>!</h5>
          <% end %>
        </div>
        <!-- Collapse button -->
        <button class="navbar-toggler animated-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent20"
          aria-controls="navbarSupportedContent20" aria-expanded="false" aria-label="Toggle navigation">
          <div class="animated-icon"><span></span><span></span><span></span></div>
        </button>
        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent20">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home <span class='sr-only'>(current)</span>".html_safe, root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Browse Listings", listings_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Create a Listing", new_listing_path, class: 'nav-link' %>
            </li>
            <% if user_signed_in? -%>
              <li><%= link_to 'View Profile', user_path(current_user.id), class: 'nav-link' %></li>
              <li><%= link_to 'My Account', edit_user_registration_path, class: 'nav-link' %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: 'nav-link' %></li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
              <li><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
            <% end %>
          </ul>
        </div>
        <!-- Collapsible content -->
      </div>
    </nav>
    <!--/.Navbar-->

    <!-- Page Wrapper -->
    <div id="page-wrapper" class="container">
      <% if notice %>
        <p class="alert alert-warning notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
    <!-- Page Wrapper -->

    <footer class="footer page-footer mt-5">
      <div class="container">
        <div class="row my-5">
          <div class="col-sm-4 text-center text-md-left">
            <p><%= link_to "Privacy Policy", privacy_policy_path %></p>
          </div><!-- end of column -->
          <div class="col-sm-4 text-center">
            <p class="footer-copyright"><small>&copy; 2019</small></p>
          </div><!-- end of column -->
          <div class="col-sm-4 text-center text-md-right">
            <p><%= link_to "Terms &amp; Conditions".html_safe, terms_path %></p>
          </div><!-- end of column -->
        </div><!-- end of .row -->
        <p class="h5 text-center mt-5 mb-4">Development Team:</p>
        <div class="row text-center pb-2">
          <div class="col-sm-4">
            <p>Jim Farrugia<br />
              <small><%= link_to "Portfolio", "https://jimfarrugia.github.io" %>&nbsp; |</small>
              <small>&nbsp;<%= link_to "Github", "https://github.com/jimfarrugia" %>&nbsp; |</small>
              <small>&nbsp;<%= link_to "Blog", "https://medium.com/@jim_farrugia" %></small>
            </p>
          </div><!-- end of column -->
          <div class="col-sm-4">
            <p>Joshua Tu<br />
              <small><%= link_to "Portfolio", "https://joshua-tu.github.io" %>&nbsp; |</small>
              <small>&nbsp;<%= link_to "Github", "https://github.com/Joshua-Tu" %></small>
            </p>
          </div><!-- end of column -->
          <div class="col-sm-4">
            <p>Nathaniel Morales<br />
              <small><%= link_to "Portfolio", "https://moralesn1.github.io" %>&nbsp; |</small>
              <small>&nbsp;<%= link_to "Github", "https://github.com/moralesn1" %></small>
            </p>
          </div><!-- end of column -->
        </div><!-- end of .row -->
      </div><!-- end .footer.container -->
    </footer>

    <script type="text/javascript">
    // Navbar animation
      $(document).ready(function () {
        $('.animated-button').on('click', function () {
          $('.animated-icon').toggleClass('open');
        });
      });
    </script>
  </body>
</html>